### ISSUE TITLE
vault-agent sidecar doesn't extend vault-agent-init's secret, but fetches new ones

### ISSUE THREAD

**Issue by TamasNeumer** [hashicorp/vault-k8s#125] opened 2020-04-17 07:51 UTC
Hello there!

## Issue

 I have a PostgresSQL database and I have set up vault with dynamic roles in order to dynamically generate database credentials for my application. By closely examining the logs I found a (potential?) bug:

- The vault-agent-init container asks the vault server for database secrets. This means that a new lease is created. Vault-agent-init writes the credentials to a file.
- Vault-agent and the application container start simultaneously. 
- Vault-agent takes some time (8 seconds  - more on this later) to fetch the (new!) secrets. 
- In the meantime my application reads the secrets generated by the vault-agent-init and connects to the database. However as the vault-agent-init is completed, its lease is not renewed, hence the secrets picked up by the application are invalidated shortly.
- Once vault-agent initializes itself it fetches a **new** pair of secrets, writes these to the file.

**Expected behavior:** Shouldn't the vault-agent keep using the vault-agent-init's lease and thus renewing the secret fetched by vault-agent-init?

### Vault versions

- `image: "hashicorp/vault-k8s:0.3.0"`
- `image: vault:1.3.2`

## Auth methods

- I'm running my setup on a GCP cluster
- I have tried it with the **k8s auth** method. Then the entire authentication and rendering (of vault-agent) takes `200ms`, so the application has no time to pick up the (soon to be expired) secrets of vault-agent-init => it picks up the new (vault-agent) secrets and things work out fine
- When using **GCP Auth** method I first get a timeout (`net/http: timeout awaiting response headers`), and the authentication only succeeds on the second attempt. (This whole process takes around 8 seconds...

```
[ERROR] auth.handler: error getting path or data from method: error="unable to sign JWT for projects/xxx/serviceAccounts/xyz@abc.iam.gserviceaccount.com using given Vault credentials: Post https://iam.googleapis.com/v1/projects/xxx/serviceAccounts/xyz@abc.iam.gserviceaccount.com:signJwt?alt=json&prettyPrint=false: Get http://IP/computeMetadata/v1/instance/service-accounts/default/token?scopes=xyz: net/http: timeout awaiting response headers" backoff=1.164255094
```

- The it backs off for a couple of seconds, retries the authentication, succeeds and writes the secrets to the file.
- But as said, the application has already picked up the files of the init-container...

## Agent config:

```hcl
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "xyz-role"
          "type" = "iam"
          "project" = "xyz"
          "service_account" = "abc@xyz.iam.gserviceaccount.com"
          "jwt_exp" = 10
        }
        "mount_path" = "auth/ourGcpAuthPath"
        "type" = "gcp"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "nothing special"
      "destination" = "/vault/secrets/jdbc.yaml"
      "create_dest_dirs" = true
    }

    "vault" = {
      "address" = "https://vault.abc.cde"
    }
```

- The agent config is the same, except the `exit_after_auth` is set to `false`.

## Deployment annotations and istio config

- Our deployment runs with the following annotations:

    ```yaml
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-configmap: our-vault-configmap
    ```
- We also have an istio sidecar running. To make it work we use a `ServiceEntry`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: vault-service-entry
  namespace: someNamespace
spec:
  hosts:
  - vault.vault.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 8200
    protocol: HTTP
  resolution: DNS
```

- The `ServiceEntry` is **NOT** located in the same namespace as our (current) deployment, however I don't believe this would be a problem.
- Istio is on the latest (1.5.1) version.

**Comment by wernerb** [comment] 2020-04-20 07:47
We are seeing the same behavior.

**Comment by jasonodonnell** [comment] 2020-04-20 19:50
Hi @TamasNeumer,

This behavior is expected.  Vault Agent Templating uses Consul Template under the hood and there is no way for Consul Template to persist the cache that keeps track of TTLs of the secrets.  Since each secret that is renewable will have a different TTL, there is no way for the init container and the sidecar container to coordinate when to renew.

Unfortunately this will be a big change to Consul Template in order to support this and the work arounds aren't the greatest: either disable the sidecar container using the `pre-populate-only` annotation (you lose auto renewal in this case), or disable the init container and have your application wait for the credentials to be rendered to disk.

We are looking into possible ways to address this issue, however, there's nothing concrete and the timeline is unknown.

Hope that helps!

**Comment by TamasNeumer** [comment] 2020-04-21 05:25
@jasonodonnell 

Thanks for the heads up!

We are using Spring Boot and until now things have been smooth, as Spring even supports "automatic" database credential swapping. I will see if I can hack my way into it. :-)

Maybe another point: Do you know why the first attempt of GCP authentication fails and backs off? If GCP auth took 200ms just like the k8s auth, I wouldn't have this problem, as the application starting up wouldn't even notice the init-container's secrets...

Maybe a way to configure the timeout?

Thanks!

**Comment by jasonodonnell** [comment] 2020-04-21 12:45
@TamasNeumer Not sure why the backoff occurs, you might try enhancing the log level to debug (there's an annotation).

Timeouts are configured using annotations as well: https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-annotations

**Comment by jasonodonnell** [comment] 2020-04-22 20:06
@TamasNeumer have you tried a newer version of Vault and experienced the same regression?

**Comment by TamasNeumer** [comment] 2020-04-24 12:03
@jasonodonnell
Thanks for the tip. Can I ask for one last advice on this topic? For us it's really an issue that the init container and the sidecar don't share the lease. I was thinking of workarounds for this problem and had the following ideas:

### Initial Solution

In our initial solution the Spring application had a `FileWatcher`, which was configured to poll the `/vault/secrets/jdbc.yaml` for changes. The process was the following:

- The init-container started -> wrote the secret
- The spring container started -> read the "old / init-container" secret which expires soon.
- The sidecar started, rendered the new secret.
- The spring application has initialized itself, picked up the file change and reconfigured its JDBC layer.
- The init-container's secret expires and Vault revokes those PostgresSQL user credentials.
- The application polls the file for changes every X seconds.

### Advanced solution with Sidecar notifying the application

The initial solution's file watcher is robust, but it is inefficient. I wanted to utilize the `agent-inject-command` so that the vault sidecar can call an `/refresh-creds` endpoint on the application. However I have read that the command **must** return with a "success" status - and now I have a bit of a "chicken vs egg" problem:

- I have disabled the init container to make the setup simpler.
- The application starts. I have added a block that waits for the vault sidecar to render and save the secret to a file.
- The vault sidecar renders the secret, wants to poke the application's `/refresh-creds`, however the application is not yet fully bootstrapped - the endpoint is not yet available. Vault-sidecar dies due to the 4xx/5xx response.

### (Possible) hacky solution?

Now the most obvious "solution" would be something like:

- Start the init-sidecar -> render the secret.
- Start the application with the init-sidecar's soon-to-be expired secrets.
- Somehow delay the start of the vault-sidecar until the application is able to server its endpoint.
- Start the vault-sidecar - let it render its secret and call the application endpoint.

### Question

- Is there a best-practice? Am I missing something?
- Should I expect the lease/credential sharing between init-container & side-car in the forseeable future?
- Is it possible to add the option to ignore the 4xx/5xx (unsuccessful) response on the agent-init-command? (i.e. add a flag which makes it go on/work)

**Comment by carlosjgp** [comment] 2020-05-12 19:57
I this error is related.
https://github.com/hashicorp/vault/issues/8245

I solve it by using agent image `1.4.0` or above (?)

**Comment by jasonodonnell** [comment] 2020-05-12 20:16
We've been working on a solution for this internally.  It's not ready to be rolled out yet but just wanted to mention that this is on our radar and something we plan to address soon.

**Comment by souvik-deepsource** [comment] 2020-08-04 14:03
@TamasNeumer Your issue just saved me from a breakdown.

**Comment by jonthegimp** [comment] 2020-08-10 13:40
@jasonodonnell , any update on the solution, or do you have another issue to follow to watch for this update?

**Comment by jasonodonnell** [comment] 2020-08-10 14:27
Hi @jonthegimp, we reviewed a solution internally that didn't require code changes but we decided to not move forward with it due to added complexity of infrastructure.  Basically we were going to alter Vault Helm to deploy a Vault Agent as a daemonset with caching and listeners enabled.  The init/sidecar would use the local agent running on the host as a proxy to Vault and it would handle all the caching.  This works well, however, it increased risk of secret exposure (it would cache all the secrets for the host) and added complexity/infrastructure to the secret injector.

We're investigating changes to Vault Agent that would allow us to persist its secret and lease cache to a memory volume so the init/sidecar can coordinate appropriately.  This is a decently large change, though, so I wouldn't expect it any earlier than Vault 1.6.

**Comment by CHR-LeeOlsen** [comment] 2020-11-10 15:57
Is there a status update on this? Seems like a pretty big issue that is impacting what I'm working on.

**Comment by jonthegimp** [comment] 2020-11-24 16:21
@jasonodonnell would you be able to provide an update, now that 1.6 has been released? I realize that this issue may not be worked in that release yet, but are there any insights you could provide on an updated timeline? Thanks much!

**Comment by jasonodonnell** [comment] 2020-11-24 17:08
Hi @jonthegimp, appreciate the ping.

Some updates on this issue:

The scope of this issue is much bigger than we anticipated. Both Vault Agent and Consul Template (what Vault Agent uses for templating) need to be extended to support persisting and loading a cache. We weren't able to get this major change into 1.6 because it requires a lot of reworking of both projects, so we're scoped to do this for Vault 1.7.

I know this bug is painful and not everyone has the flexibility to design around it. There is a small workaround which might be acceptable for your use case which I've been experimenting with.

Vault Agent has a caching mode which can be enabled via the config. This creates an in-memory cache. Vault Agent can also be used as a proxy for other clients. Combining these two features into a DaemonSet and reconfiguring your sidecars to use the agent proxy running on that host eliminates this issue because the agent running on the host is caching the requests.

I have an example here if you want to experiment with it: https://github.com/jasonodonnell/vault-agent-demo/tree/daemonset.

There's basically one small change I would need to make to Vault K8s that sets the downward API `HOST_IP` environment variable on the agent containers. By doing this it would be very easy to use the `vault.hashicorp.com/service` annotation to redirect the agents to the proxy.

We discussed internally if we should just make the DaemonSet infrastructure part of Vault Helm but ultimately decided we shouldn't because the added infrastructure/complexity seemed risky compared to sharing a persisted cache.

**Comment by jonthegimp** [comment] 2020-12-21 18:23
@jasonodonnell, if you have the time to optimize Vault K8s for this change, I would be interested in experimenting with this.

**Comment by wernerb** [comment] 2020-12-21 21:07
The memory cache sounds a lot better than having hosts / daemons cache everything. A parallel is with kiam or kube2iam which did the same (hosts have all the secrets). 

I don't want to discourage any work, the security implications must be front and center though.

Also there are cases beyond just init container/sidecar. We have observed that the vault agent in rare occurrences can crash. This results in a vault token and leases expiring even when the container restarts. I know that the app is supposed to watch for changes to files but this is not doable for some libraries (datastax cassandra is unable to close and reopen sessions)

**Comment by jonthegimp** [comment] 2021-03-18 20:17
@jasonodonnell I was reading the v0.9.0 changelog; does [GH-229](https://github.com/hashicorp/vault-k8s/pull/229) resolve this issue?

**Comment by jasonodonnell** [comment] 2021-03-18 20:38
@jonthegimp Indeed it does! The catch is that it requires Vault 1.7 which is not yet GA. We expect 1.7 to go GA next week but you can try 1.7 RC1 with the new injector today!

**Comment by jonthegimp** [comment] 2021-03-18 20:52
@jasonodonnell awesome - thank you so much to you and the team, great work!

**Comment by jasonodonnell** [comment] 2021-05-21 18:52
Closing since persistent caching has been released.

**Closed by jasonodonnell** 2021-05-21 18:52 UTC
Labels: injector, question
