### ISSUE TITLE
TLS handshake error when running 2 instances of Agent Inject pod is running.

### ISSUE THREAD

**Issue by MKruger777** [hashicorp/vault-k8s#181] opened 2020-09-23 13:57 UTC
**Describe the bug:**
There exist inner pod dependencies within our k8s cluster.
By this is meant that certain pods rely/depend on the existence of other pods for startup.
In the case where the pod being relied on does not exist - the pods depending on it will either end up in a failed state or not start at all.

In this case, it was pods relying on the Agent Inject to inject them.
All works fine until a drain is done on the node (this happens sporadically and is handled by Kured) where the Agent Inject as well as a pod depending on it for injection runs.

**Scenario / Reproducing:**
node_x has the following pods on it:
AgentInjector_pod
PleaseInjectMe_pod

1. During a rolling update node_x gets drained.
2. All the pods on node_x get evicted and startup on an other node(s).
3. A race between the startup of the AgentInjector_pod and the PleaseInjectMe_pod starts.
4. If the PleaseInjectMe_pod is first to start and the AgentInjector_pod is not yet started - the PleaseInjectMe_pod ends up in a failed state, as it was depending on the injection from the AgentInjector_pod.

**Possible solution:**
Decided on changing the replicas count to 2 of AgentInjector_pod on the cluster.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-agent-injector
spec:
  replicas: 2
```
Used podAntiAffinity to guarantee that these 2 injectors never end up on the same node, thereby always having an injector running during rolling updates.

**Result:**
The 2 replicas of the AgentInjector_pod does indeed never end up on the same node due to the added podAntiAffinity.
Preliminary results indicated that the injection does still work - i.e. when pods get started that requires this it works. 
But this was not consistent...

From the logs of each injector we see the following:
10.137.4.82 = the aks tunnelfront pod

```
kubectl logs vault-agent-injector-5797456cb5-9bz6v -n myns
Listening on ":8080"...
2020-09-23T02:26:45.218Z [INFO]  handler: Starting handler..
Updated certificate bundle received. Updating certs...
2020/09/23 02:41:16 http: TLS handshake error from 10.137.4.82:40278: remote error: tls: bad certificate
2020/09/23 02:48:40 http: TLS handshake error from 10.137.4.82:54764: remote error: tls: bad certificate
2020/09/23 02:48:40 http: TLS handshake error from 10.137.4.82:54762: remote error: tls: bad certificate
2020-09-23T02:57:56.761Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T03:31:17.088Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T04:37:57.648Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T04:54:37.833Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 05:11:18 http: TLS handshake error from 10.137.4.82:51608: remote error: tls: bad certificate
2020-09-23T05:44:38.386Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 06:01:18 http: TLS handshake error from 10.137.4.82:36302: remote error: tls: bad certificate
Error updating MutatingWebhookConfiguration: etcdserver: request timed out
2020/09/23 07:57:59 http: TLS handshake error from 10.137.4.82:38074: remote error: tls: bad certificate
2020-09-23T08:31:19.793Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T09:38:00.429Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T10:28:00.989Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T11:18:01.516Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 11:34:41 http: TLS handshake error from 10.137.4.82:37144: remote error: tls: bad certificate
2020-09-23T11:38:03.362Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 11:51:21 http: TLS handshake error from 10.137.4.82:41464: remote error: tls: bad certificate
2020-09-23T12:24:42.222Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s



kubectl logs vault-agent-injector-5797456cb5-q7tsh -n myns
2020-09-22T19:33:40.691Z [INFO]  handler: Starting handler..
Listening on ":8080"...
Updated certificate bundle received. Updating certs...
2020/09/22 19:33:41 http: TLS handshake error from 10.137.4.66:57216: no certificate available
2020-09-22T20:17:52.977Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-22T21:24:33.563Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/22 21:57:53 http: TLS handshake error from 10.137.4.82:50302: remote error: tls: bad certificate
2020/09/22 22:47:54 http: TLS handshake error from 10.137.4.82:35164: remote error: tls: bad certificate
2020/09/22 23:37:54 http: TLS handshake error from 10.137.4.82:48094: remote error: tls: bad certificate
2020/09/22 23:54:34 http: TLS handshake error from 10.137.4.82:52486: remote error: tls: bad certificate
2020/09/23 00:10:20 http: TLS handshake error from 10.137.4.82:55090: remote error: tls: bad certificate
2020-09-23T01:51:16.089Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 02:18:06 http: TLS handshake error from 10.137.4.82:51226: remote error: tls: bad certificate
2020-09-23T02:18:07.062Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:18:07.065Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:18:07.149Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:24:36.441Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:26:33.683Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:26:33.692Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 02:26:33 http: TLS handshake error from 10.137.4.82:39766: remote error: tls: bad certificate
2020-09-23T02:26:42.091Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:26:44.504Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:48:40.147Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:48:40.148Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:48:40.149Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T02:48:40.150Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 03:14:36 http: TLS handshake error from 10.137.4.82:49222: remote error: tls: bad certificate
2020-09-23T03:47:57.202Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 04:04:37 http: TLS handshake error from 10.137.4.82:34074: remote error: tls: bad certificate
2020/09/23 04:21:17 http: TLS handshake error from 10.137.4.82:38476: remote error: tls: bad certificate
2020-09-23T05:27:58.212Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T06:17:58.689Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T06:34:38.803Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 06:51:18 http: TLS handshake error from 10.137.4.82:49104: remote error: tls: bad certificate
2020/09/23 07:07:59 http: TLS handshake error from 10.137.4.82:53344: remote error: tls: bad certificate
2020/09/23 07:24:39 http: TLS handshake error from 10.137.4.82:57710: remote error: tls: bad certificate
2020/09/23 07:41:19 http: TLS handshake error from 10.137.4.82:33750: remote error: tls: bad certificate
2020-09-23T08:14:39.581Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T08:47:59.981Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020/09/23 09:04:40 http: TLS handshake error from 10.137.4.82:55304: remote error: tls: bad certificate
2020/09/23 09:21:20 http: TLS handshake error from 10.137.4.82:59608: remote error: tls: bad certificate
2020-09-23T09:54:40.589Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T09:54:47.467Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T10:11:20.817Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T10:44:41.104Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T11:01:21.329Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T12:08:02.009Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
```

**Expected behavior**
No errors in the logfile.
When there is just 1 replica running all seems normal.

Example of only 1 instance running logfile:
```
2020-09-23T12:41:56.086Z [INFO]  handler: Starting handler..
Listening on ":8080"...
Updated certificate bundle received. Updating certs...
2020-09-23T12:44:03.388Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T12:45:13.314Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
2020-09-23T12:58:02.612Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
```

**Environment**
  * AKS
  * k8s version - 1.17.9
  * Agent Inject: docker/hashicorp/vault-k8s:0.4.0

**Additional context**
My apologies upfront if this is not a bug!
What could be causing this? and is it possible to run 2 vault-agent-injectors in one cluster at all?
Any alternatives or suggestions are obviously welcome : -)

**Comment by jasonodonnell** [comment] 2020-09-28 14:32
Duplicate of #141, but you can find a work around here: https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls

**Closed** 2020-09-28 14:33 UTC
Labels: bug

**Comment by MKruger777** [comment] 2020-09-28 14:36
Hey @jasonodonnell,  many thanks for checking this out and the feedback! Much appreciated :-)
