### ISSUE TITLE
AKS Vault agent Injector annotations-patches are not updating /vaults/secrets

### ISSUE THREAD

**Issue by woowil** [hashicorp/vault-k8s#114] opened 2020-04-01 14:24 UTC
I'm using Vault-Helm chart to deploy Vault on Azure Kubernetes Services. 

I have created an issuer on the Vault-helm repo with detailed information. I assume this problem is partly related to the injector image and admission webhook. 

Any suggestions, please?

https://github.com/hashicorp/vault-helm/issues/244

**Comment by tvoran** [comment] 2020-07-01 01:28
Closing, duplicate of https://github.com/hashicorp/vault-helm/issues/244

**Closed by tvoran** 2020-07-01 01:28 UTC
Labels: chart, question
