### ISSUE TITLE
Vault init container can't connect fo vault: Connection refused.

### ISSUE THREAD

**Issue by TamasNeumer** [hashicorp/vault-k8s#29] opened 2020-01-03 09:22 UTC
Hi!

I was playing around with the [secret injection](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/) that was released on 19th of December. I'm not yet sure if I have found a bug, or it’s just me doing something wrong:

**The setup works, if the deployment is in the same namespace as vault**

I went through the blog/tutorial and it all works. I have set up vault to be in a kubernetes namespace “vault”. (Installed with dev mode on `true)`. Then the app was deployed in the same namespace. Everything works fine - the init container picks up the secret etc.

**Connection refused, if application deployed to default namespace**

Then I wanted to deploy the same demo-deployment to the `default` namespace.  To make it work with the policy I have modified the “SA_namespace” from `vault` to `default`:

```
vault write auth/kubernetes/role/myapp \
   bound_service_account_names=app \
   bound_service_account_namespaces=default \
   policies=app \
   ttl=1h
```

Then set the context to use the default namespace by default and deployed the app. However the vault init contianer **was not** able to log in to vault:

```
[ERROR] auth.handler: error authenticating: error="Put http://vault.vault.svc:8200/v1/auth/kubernetes/login: dial tcp 10.74.11.52:8200: connect: connection refused" backoff=1.211726213
```

**What I have investigated (in the default namespace)**

- I attached my terminal to the init-container. `nslookup` works, the IP and the port are correct. However I couldn't ping any service from the init-contianer. (Not even www.google.com etc.)
- I have written a deployment myself, using the same `vault:1.3.1` image as an init-container and passed the `sleep 3600` as an argument to it. Then I attached the terminal to this container and from here I could log in to vault, get the token etc - so everything worked fine.
- Needless to say, but I have did the same with a normal "debugging" pod, and successfully logged into vault, as described [here](https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s)

**Comment by jasonodonnell** [comment] 2020-01-06 16:55
Hi @TamasNeumer, can you provide more information about your environment?

* What version of Kube are you using?
* Are you using a managed Kube service such as GKS, EKS?
* Is your network fabric working correctly? `kubectl get pods -n kube-system`

**Comment by jasonodonnell** [comment] 2020-01-07 15:04
@TamasNeumer Can you also provide me with the output from this command by execing into the vault-agent container:

```bash
cat /etc/resolv.conf
```

**Comment by TamasNeumer** [comment] 2020-01-07 15:54
Hi!

- What version of Kube are you using? -> 1.13.11-gke.14
- Are you using a managed Kube service such as GKS, EKS? -> GKE
- Is your network fabric working correctly? `kubectl get pods -n kube-system` -> Yes. 
- If you exec into the injected init container, can you ping the following ...?
  - No. Response: `ping: bad address 'http://vault.vault.svc.cluster.local:8200/v1/auth/kubernetes/login'`
  - Interesting because `nslookup vault.vault.svc.cluster.local` resolves to `Address 1: 10.74.11.52 vault.vault.svc.cluster.local`. But then I can: `ping vault.vault.svc.cluster.local` but in this case I get `ping: permission denied (are you root?)`

`cat /etc/resolv.conf` gives me the following:

```
nameserver 10.74.0.10
search default.svc.cluster.local svc.cluster.local cluster.local c.<project-name>.internal google.internal
options ndots:5
```

**Comment by jasonodonnell** [comment] 2020-01-07 16:12
@TamasNeumer How did you install the injector? Manual or via helm?

I suspect there's an issue with how the Vault address is being rendered: `http://vault.vault.svc:8200/v1/auth/kubernetes/login`.  I think this might need to be `http://vault.vault.svc.cluster.local:8200/v1/auth/kubernetes/login`.

If you installed manually, change this value to include `cluster.local`: https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-deployment.yaml#L36

If you installed via helm, clone the helm repo and change this value to include `cluster.local`: https://github.com/hashicorp/vault-helm/blob/master/templates/injector-deployment.yaml#L43

Let me know if this helps!

**Comment by TamasNeumer** [comment] 2020-01-08 08:51
@jasonodonnell 

Hi!

It turns out istio was enabled on our default namespace. Once disabled the deployment works.
Sorry for the mess. Though it would be interesting to investigate the integration with istio, as I think it's going to be a popular combination.

Should I rename the ticket and change the topic to istio integration or close it?

Thanks for the help!

**Comment by jasonodonnell** [comment] 2020-01-08 10:21
Hi @TamasNeumer, let's close this. It you want to open an issue about istio, please open a new issue.

**Closed by jasonodonnell** 2020-01-08 10:21 UTC

**Comment by therealsamlin** [comment] 2020-05-12 07:10
@TamasNeumer 

Did you get around this eventually? I'm bumping into the same issue, secrets retrieval works only with pods that don't have istio-proxy in them

Cheers,

**Comment by TamasNeumer** [comment] 2020-05-22 20:14
@therealsamlin 

Hi! 
Sorry for the late response.

Yes, I managed to get it working. Take a look at this issue's discussion:
https://github.com/hashicorp/vault-k8s/issues/41

**Comment by renejesusgv** [comment] 2020-06-02 06:23
@therealsamlin hi Tamas, I'm stuck with the same issue, I have the service entry  and the annotations  applied. With the current setup, istio-proxy runs before vault-agent-init, inside the vault-agent-init container the address apparently works out well:

`$ nslookup vault.vault.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      vault.vault.svc.cluster.local
Address 1: 100.64.167.57 vault.vault.svc.cluster.local`

But the logs: 
`2020-06-02T06:09:51.251Z [INFO]  auth.handler: authenticating
2020-06-02T06:09:51.310Z [ERROR] auth.handler: error authenticating: error="Put http://vault.vault.svc:8200/v1/auth/kubernetes/login: dial tcp 100.64.167.57:8200: connect: connection refused" backoff=1.813357809`
 
My vault status:

`vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.4.0
Cluster Name    vault-cluster-04d78995
Cluster ID      2096f37b-5823-186e-4f5d-a9363322b188
HA Enabled      false`

My vault pods:
`kubectl get pods  -n vault
NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 1/1     Running   0          9h
vault-agent-injector-7b468b946b-lgcj9   2/2     Running   0          4h29m`


Do you see anything suspicious?
Thanks in advance.

**Comment by TamasNeumer** [comment] 2020-06-07 18:59
> : I could make it work with the traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
> annotation, looks like vault agent container is running after istio-proxy ignoring the vault.hashicorp.com/agent-init-first: "true" annotation.

Hi!

Thanks for the heads up. I will also test the `traffic.sidecar.istio.io/excludeOutboundPorts: "8200"` fix.

Cheers,
Tamas

**Comment by nitingadekar** [comment] 2020-07-17 18:07
The annotation vault.hashicorp.com/agent-init-first: "true" worked for me when used with istio sidecar and init pods. Thanks for the fix. 

As it is not clearly documented, can you confirm the case @TamasNeumer , @jasonodonnell  in which, my vault and injector are in "vault" namespace, and I want to use the injector in all the other namespaces, do I need to create new service account and map it to the vault k8s role for every namespace? 

I have been looking for a resolution from a long time, your response will be appreciated.

**Comment by jasonodonnell** [comment] 2020-07-20 13:36
@nitingadekar Yes, the K8s auth method does support wildcards, though:

```
vault write auth/kubernetes/role/demo \
    bound_service_account_names=vault-auth \
    bound_service_account_namespaces=* \
    policies=default \
    ttl=1h
```

**Comment by semihural** [comment] 2021-01-15 12:58
Hi @TamasNeumer , @nitingadekar, @jasonodonnell 

I also stuck with the same issue but none of them help me to fixed the issue.. the only thing that I did not try is `traffic.sidecar.istio.io/excludeOutboundPorts: "8200"` cause ı do not understand where should I add this..

I also posted here but here are the details.

I am using on-prem k8s v1.19 and Istio with 1.8.0.. I got stuck to run them together properly when I inject istio mesh to the `hub-dev` where our microservices are running. Vault is running `dev` namespace.

The first issue I had is Vault and Istio sidecar is not running properly somehow and the application can not able to init as below. I tried to use below annotations to init first vault but it did not solve below issue.

   
 - vault.hashicorp.com/agent-init-first: true  
 - vault.hashicorp.com/agent-inject: true

Here are the outputs of pod status and describe

    $ kubectl get pods -n hub-dev
        NAME                                     READY   STATUS     RESTARTS   AGE
        oneapihub-mp-dev-59f7685455-5kmft        0/3     Init:0/2   0          19
        
    $ kubectl describe pod oneapihub-mp-dev-59f7685455-5kmft -n hub-dev

    Init Containers:
      vault-agent-init:
        Container ID:  
        State:          Running
          Started:      Fri, 15 Jan 2021 13:54:30 +0300
        Ready:          False
      istio-validation:
        Container ID:
        Image:         reg-dhc.app.corpintra.net/i3-mirror/docker.io_istio_proxyv2:1.8.0
        State:          Waiting
         Reason:       PodInitializing
        Ready:          False
    Containers:
          oneapihub-mp:
            Container ID:
            State:          Waiting
              Reason:       PodInitializing
            Ready:          False
          istio-proxy:
            Container ID:
            State:          Waiting
              Reason:       PodInitializing
            Ready:          False
      istio-proxy:
        Container ID:
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False

        Normal  Pulled     16m   kubelet, xx-kube-node07  Container image "docker.io_vault:1.5.2" already present on machine
        Normal  Created    16m   kubelet, xx-kube-node07  Created container vault-agent-init
        Normal  Started    16m   kubelet, xx-kube-node07  Started container vault-agent-init

When I tried below annotation, it fixed the above issue, but this time when pod starts to run it can not able to find `/vault/secrets` path but somehow after that it can be read when I checked the logs of proxy and application and `/vault/secrets` folder is exist inside pod.
        

     - vault.hashicorp.com/agent-pre-populate: "false"

Here the logs of app even if folder exists

    $ kubectl get pods -n hub-dev
    oneapihub-mp-dev-78449b8cf6-qbqhn        3/3     Running   0          9m31s

    $ kubectl logs -f oneapihub-mp-dev-78449b8cf6-qbqhn -n hub-dev -c oneapihub-mp
    
    > market-place@1.0.0 start:docker /usr/src/app
    > node app.js
    
    {"message""devMessage":"SECRET_READ_ERROR","data":"","exception":"ENOENT: no such file or directory, open '/vault/secrets/database'","stack":"Error: ENOENT: no such file or directory, open '/vault/secrets/database'->

    / $ cd /vault/secrets
    /vault/secrets $ ls
    database  jenkins
    /vault/secrets $

Here I have some PUT error which might related with Vault itself but I am confuse how then Vault can inject the secrets.

     $ kubectl logs -f oneapihub-mp-dev-78449b8cf6-qbqhn -n hub-dev -c vault-agent

    2021-01-15T11:21:13.477Z [ERROR] auth.handler: error authenticating: error="Put "http://vault.dev.svc:8200/v1/auth/kubernetes/login": dial tcp 10.254.30.115:8200: connect: connection refused" backoff=2.464775515
    ==> Vault agent started! Log data will stream in below:
    
    ==> Vault agent configuration:
    
                         Cgo: disabled
                   Log Level: info
                     Version: Vault v1.5.2
                 Version Sha: 685fdfa60d607bca069c09d2d52b6958a7a2febd
    
    2021-01-15T11:21:15.942Z [INFO]  auth.handler: authenticating
    2021-01-15T11:21:15.966Z [INFO]  auth.handler: authentication successful, sending token to sinks
    2021-01-15T11:21:15.966Z [INFO]  sink.file: token written: path=/home/vault/.vault-token

And lastly when I checkted the istio-proxy logs I can see that GET or PUT request returns 200.

    $ kubectl logs -f oneapihub-mp-dev-78449b8cf6-h8s8j -n hub-dev -c istio-proxy

    021-01-15T11:35:04.352221Z	warning	envoy filter	mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
    [2021-01-15T11:35:05.557Z] "PUT /v1/auth/kubernetes/login HTTP/1.1" 200 - "-" 1294 717 8 8 "-" "Go-http-client/1.1" "a082698b-d1f7-4aa5-9db5-01d86d5093ef" "vault.dev.svc:8200" "10.6.24.55:8200" outbound|8200||vault.dev.svc.cluster.local 10.6.19.226:55974 10.254.30.115:8200 10.6.19.226:60478 - default
    2021-01-15T11:35:05.724833Z	info	Envoy proxy is ready
    [2021-010.6.19.226:41888 - default
    [2021-01-15T11:35:05.596Z] "GET /v1/secret/data/oneapihub-marketplace/database HTTP/1.1" 200 - "-" 0 400 0 0 "-" "Go-http-client/1.1" "d7d10c1f-c445-44d1-b0e3-bb9ae7bbc2f0" "vault.dev.svc:8200" "10.6.24.55:8200" outbound|8200||vault.dev.svc.cluster.local 10.6.19.226:55974 10.254.30.115:8200 10.6.19.226:41900 - default
    [2021-01-15T11:35:05.591Z] "PUT /v1/auth/token/renew-self HTTP/1.1" 200 - "-" 15 717 8 8 "-" "Go-http-client/1.1" "56705e5c-c966-4bc8-8187-7ca5bb2b4abe" "vault.dev.svc:8200" "10.6.24.55:8200" outbound|8200||vault.dev.svc.cluster.local 10.6.19.226:37388 10.254.30.115:8200 10.6.19.226:41890 - default
    [2021-01-15T11:35:05.602Z] "GET /v1/secret/data/oneapihub-marketplace/jenkins HTTP/1.1" 200 - "-" 0 284 0 0 "-" "Go-http-client/1.1" "1b6d8601-18df-4f32-8722-162aa785c476" "vault.dev.svc:8200" "10.6.24.55:8200" outbound|8200||vault.dev.svc.cluster.local 10.6.19.226:55974 10.254.30.115:8200 10.6.19.226:41902 - default

**Comment by agrawalarpit01** [comment] 2023-05-30 20:05
@semihural I am also stuck with the issue you mentioned, can you please help let me know, if you able to find the root cause of this?
