### ISSUE TITLE
Not able to export Environment variable inside pod using vault agent

### ISSUE THREAD

**Issue by awsompankaj** [hashicorp/vault-k8s#186] opened 2020-10-19 08:29 UTC
Hello We have installed vault in HA mode in our kubernetes environment which is working fine without any issues.

we have created a secret inside vault which we want to export it as environment variable.

we have tried below steps from the documentation.

https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example

We have tried to export one variable using below deployment.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "internal/data/database/config" -}}
                  #!/bin/bash
                  export username={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-database-config: /bin/sh -c "source /vault/secrets/database-config"
      labels:
        app: orgchart
    spec:
      serviceAccountName: internal-app
      containers:
        - name: orgchart
          image: de1gks1crgtst.admnet.vodafone.com/library/app:0.0.1
          args: ["sh", "-c", "source /vault/secrets/database-config"]

A file is created at /vautl/secrets/database-config but it is not getting in env.

/app # env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://100.64.0.1:443
HOSTNAME=orgchart-7d95b4c7bc-g7cqj
SHLVL=1
HOME=/root
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=100.64.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://100.64.0.1:443
KUBERNETES_SERVICE_HOST=100.64.0.1
PWD=/app
/app #

once i exec ti pod and do source it work then only
/app # env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://100.64.0.1:443
HOSTNAME=orgchart-7d95b4c7bc-g7cqj
SHLVL=1
HOME=/root
**username=redhat@123**
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=100.64.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://100.64.0.1:443
KUBERNETES_SERVICE_HOST=100.64.0.1
PWD=/app

**Comment by cassador** [comment] 2020-10-23 08:40
I am also facing exactly the same issue and was pointed to a discussion saying it might help me resolve the issue.

The link for discussion:
https://discuss.hashicorp.com/t/vault-helm-and-kubernetes-environment-variables/4973/7

Adding also the link on issue where was the non working env variable mentioned:
https://github.com/hashicorp/vault-k8s/issues/110
It started as different issue but when i mentioned the env var issue i was pointed to the discussion which i shared the link.

@awsompankaj  if you will be able to get this working please share the information as i am stucked there for couple of weeks now.

**Comment by mrccord** [comment] 2020-10-27 03:07
Try using this one:

          image: jweissig/app:0.0.1
          command: ["/bin/sh", "-c"]
          args: [". /vault/secrets/config && env >> /app/secret.txt && sleep 600"]

It's work for me.

**Comment by cassador** [comment] 2020-10-27 08:22
@mrccord that worked like miracle i will try to implement it for other application's but for that specific use case it's working like charm

**Comment by awsompankaj** [comment] 2020-10-29 09:08
@cassador for me in file /app/secret.txt it has the environment value but when i run env inside the pod, it was not there.

**Comment by mrccord** [comment] 2020-10-29 19:22
@awsompankaj that happens when you run a new bin/sh, because is a new instance, think when you run kubectl exec -it pod-name -- bin/sh is like a new user, it does'nt have the environment variables, but if you run the command . /vault/secrets/* that work fine

**Comment by ToxicWar** [comment] 2020-11-18 02:42
@awsompankaj it's not a bug (check @mrccord reply)

https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example

Please check processes in your pod.
You will see main process which run "source /vault/secrets/config && <entrypoint script>"
Only this process has information about your environment variable (username).

When you connect to pod via `kubectl exec -it <pod-name> -- sh`, you will have a new environment without changes you did in your main process.

**Comment by Sleepy-GH** [comment] 2020-11-25 16:21
It would be nice having this as a feature though. I'm using quite a few helm charts which don't all support loading secrets from files and in which I can't override the command or args.

**Comment by yashbhutwala** [comment] 2021-03-19 13:09
See #14, #45 and https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example

**Comment by jasonodonnell** [comment] 2021-04-08 15:42
Closing as duplicate of #14

**Closed by jasonodonnell** 2021-04-08 15:42 UTC
Labels: bug

**Comment by abhishekkamal96** [comment] 2021-05-11 11:09
> Hello We have installed vault in HA mode in our kubernetes environment which is working fine without any issues.
> 
> we have created a secret inside vault which we want to export it as environment variable.
> 
> we have tried below steps from the documentation.
> 
> https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
> 
> We have tried to export one variable using below deployment.
> 
> apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: orgchart
> labels:
> app: orgchart
> spec:
> selector:
> matchLabels:
> app: orgchart
> replicas: 1
> template:
> metadata:
> annotations:
> vault.hashicorp.com/agent-inject: "true"
> vault.hashicorp.com/role: "internal-app"
> vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
> vault.hashicorp.com/agent-inject-template-database-config: |
> {{ with secret "internal/data/database/config" -}}
> #!/bin/bash
> export username={{ .Data.data.password }}
> {{- end }}
> vault.hashicorp.com/agent-inject-command-database-config: /bin/sh -c "source /vault/secrets/database-config"
> labels:
> app: orgchart
> spec:
> serviceAccountName: internal-app
> containers:
> - name: orgchart
> image: de1gks1crgtst.admnet.vodafone.com/library/app:0.0.1
> args: ["sh", "-c", "source /vault/secrets/database-config"]
> 
> A file is created at /vautl/secrets/database-config but it is not getting in env.
> 
> /app # env
> KUBERNETES_SERVICE_PORT=443
> KUBERNETES_PORT=tcp://100.64.0.1:443
> HOSTNAME=orgchart-7d95b4c7bc-g7cqj
> SHLVL=1
> HOME=/root
> TERM=xterm
> KUBERNETES_PORT_443_TCP_ADDR=100.64.0.1
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> KUBERNETES_PORT_443_TCP_PORT=443
> KUBERNETES_PORT_443_TCP_PROTO=tcp
> KUBERNETES_SERVICE_PORT_HTTPS=443
> KUBERNETES_PORT_443_TCP=tcp://100.64.0.1:443
> KUBERNETES_SERVICE_HOST=100.64.0.1
> PWD=/app
> /app #
> 
> once i exec ti pod and do source it work then only
> /app # env
> KUBERNETES_SERVICE_PORT=443
> KUBERNETES_PORT=tcp://100.64.0.1:443
> HOSTNAME=orgchart-7d95b4c7bc-g7cqj
> SHLVL=1
> HOME=/root
> **username=redhat@123**
> TERM=xterm
> KUBERNETES_PORT_443_TCP_ADDR=100.64.0.1
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> KUBERNETES_PORT_443_TCP_PORT=443
> KUBERNETES_PORT_443_TCP_PROTO=tcp
> KUBERNETES_SERVICE_PORT_HTTPS=443
> KUBERNETES_PORT_443_TCP=tcp://100.64.0.1:443
> KUBERNETES_SERVICE_HOST=100.64.0.1
> PWD=/app

Did you get any solution for this @awsompankaj

**Comment by Sleepy-GH** [comment] 2021-05-12 01:03
@abhishekkamal96 you cannot currently inject them as environment variables because of the nature of the solution. The pod annotations for vault get processed by the vault agent sidecar container. This means that when you export a var it will only be exported in that sidecar container and not in your application container. That's why the solution is to render it into a file which is in a shared volumeMount so your application container can access the rendered credential file.

**Comment by abhishekkamal96** [comment] 2021-05-12 06:52
@Sleepy-GH Thank you for the reply. Is there any other way by which I can inject the secrets as environment variable?

**Comment by JWebDev** [comment] 2022-02-23 06:30
Hi. Today I have an identical problem.
https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example
This example doesn't work.

The ticket has been closed, but the issue has not been resolved. 
A file with a secret in a container, but source /vault/secret/secret has no effect.

Or this problem can only be solved with CSI?
https://www.vaultproject.io/docs/platform/k8s/csi

Thanks for the answer

**Comment by tirelibirefe** [comment] 2022-12-14 16:38
Correct,
Everybody send the link of the example page but the example doesn't work.
"command" overrides the ENTRYPOINT in dockerfile.  That's why the example is not valid for dotnet containers.
Currently I couldn't have found any way to inject secrets as environment variables on a dotnet application. If you were able to figure out , please share...

**Comment by brauliogr** [comment] 2023-03-29 22:52
I'm having the same problem, I have a java app, and it receives environment variables, I'm having trouble adding the vault variables to the environment variableI have the same problem, I have a java app and I am not able to inject variables into its.

**Comment by brauliogr** [comment] 2023-03-29 22:52
I have the same problem, I have a java app and I am not able to inject variables into it
